#pragma once

#include "WinUHidDevs.h"

typedef struct _WINUHID_STEAM_CONTROLLER* PWINUHID_STEAM_CONTROLLER;

#define WINUHID_STEAM_CONTROLLER_VENDOR_ID 0x28DE
#define WINUHID_STEAM_CONTROLLER_TRITON_BLE_PRODUCT_ID 0x1303

#define WINUHID_STEAM_CONTROLLER_FEATURE_REPORT_ID 0x01
#define WINUHID_STEAM_CONTROLLER_FEATURE_REPORT_BYTES 64

#define WINUHID_STEAM_CONTROLLER_REPORT_ID_INPUT 0x42
#define WINUHID_STEAM_CONTROLLER_REPORT_ID_BATTERY 0x43
#define WINUHID_STEAM_CONTROLLER_REPORT_ID_INPUT_BLE 0x45
#define WINUHID_STEAM_CONTROLLER_REPORT_ID_WIRELESS_STATUS_X 0x46
#define WINUHID_STEAM_CONTROLLER_REPORT_ID_WIRELESS_STATUS 0x79

#define WINUHID_STEAM_CONTROLLER_BUTTON_A 0x00000001u
#define WINUHID_STEAM_CONTROLLER_BUTTON_B 0x00000002u
#define WINUHID_STEAM_CONTROLLER_BUTTON_X 0x00000004u
#define WINUHID_STEAM_CONTROLLER_BUTTON_Y 0x00000008u
#define WINUHID_STEAM_CONTROLLER_BUTTON_QAM 0x00000010u
#define WINUHID_STEAM_CONTROLLER_BUTTON_R3 0x00000020u
#define WINUHID_STEAM_CONTROLLER_BUTTON_VIEW 0x00000040u
#define WINUHID_STEAM_CONTROLLER_BUTTON_R4 0x00000080u
#define WINUHID_STEAM_CONTROLLER_BUTTON_R5 0x00000100u
#define WINUHID_STEAM_CONTROLLER_BUTTON_R 0x00000200u
#define WINUHID_STEAM_CONTROLLER_BUTTON_DPAD_DOWN 0x00000400u
#define WINUHID_STEAM_CONTROLLER_BUTTON_DPAD_RIGHT 0x00000800u
#define WINUHID_STEAM_CONTROLLER_BUTTON_DPAD_LEFT 0x00001000u
#define WINUHID_STEAM_CONTROLLER_BUTTON_DPAD_UP 0x00002000u
#define WINUHID_STEAM_CONTROLLER_BUTTON_MENU 0x00004000u
#define WINUHID_STEAM_CONTROLLER_BUTTON_L3 0x00008000u
#define WINUHID_STEAM_CONTROLLER_BUTTON_STEAM 0x00010000u
#define WINUHID_STEAM_CONTROLLER_BUTTON_L4 0x00020000u
#define WINUHID_STEAM_CONTROLLER_BUTTON_L5 0x00040000u
#define WINUHID_STEAM_CONTROLLER_BUTTON_L 0x00080000u
#define WINUHID_STEAM_CONTROLLER_TOUCH_RIGHT_STICK 0x00100000u
#define WINUHID_STEAM_CONTROLLER_TOUCH_RIGHT_PAD 0x00200000u
#define WINUHID_STEAM_CONTROLLER_CLICK_RIGHT_PAD 0x00400000u
#define WINUHID_STEAM_CONTROLLER_CLICK_RIGHT_TRIGGER 0x00800000u
#define WINUHID_STEAM_CONTROLLER_TOUCH_LEFT_STICK 0x01000000u
#define WINUHID_STEAM_CONTROLLER_TOUCH_LEFT_PAD 0x02000000u
#define WINUHID_STEAM_CONTROLLER_CLICK_LEFT_PAD 0x04000000u
#define WINUHID_STEAM_CONTROLLER_CLICK_LEFT_TRIGGER 0x08000000u
#define WINUHID_STEAM_CONTROLLER_TOUCH_RIGHT_AUX 0x10000000u
#define WINUHID_STEAM_CONTROLLER_TOUCH_LEFT_AUX 0x20000000u

typedef enum _WINUHID_STEAM_CONTROLLER_RAW_HID_REPORT_TYPE {
	WinUHidSteamControllerRawHidReportTypeOutput = 1,
	WinUHidSteamControllerRawHidReportTypeFeature = 2,
} WINUHID_STEAM_CONTROLLER_RAW_HID_REPORT_TYPE;

#include <pshpack1.h>

typedef struct _WINUHID_STEAM_CONTROLLER_IMU_STATE {
	ULONG Timestamp;
	SHORT AccelX;
	SHORT AccelY;
	SHORT AccelZ;
	SHORT GyroX;
	SHORT GyroY;
	SHORT GyroZ;
} WINUHID_STEAM_CONTROLLER_IMU_STATE, *PWINUHID_STEAM_CONTROLLER_IMU_STATE;
typedef CONST WINUHID_STEAM_CONTROLLER_IMU_STATE* PCWINUHID_STEAM_CONTROLLER_IMU_STATE;

typedef struct _WINUHID_STEAM_CONTROLLER_INPUT_REPORT {
	UCHAR ReportId;
	UCHAR SequenceNumber;
	ULONG Buttons;
	SHORT TriggerLeft;
	SHORT TriggerRight;
	SHORT LeftStickX;
	SHORT LeftStickY;
	SHORT RightStickX;
	SHORT RightStickY;
	SHORT LeftPadX;
	SHORT LeftPadY;
	USHORT PressureLeft;
	SHORT RightPadX;
	SHORT RightPadY;
	USHORT PressureRight;
	WINUHID_STEAM_CONTROLLER_IMU_STATE Imu;
} WINUHID_STEAM_CONTROLLER_INPUT_REPORT, *PWINUHID_STEAM_CONTROLLER_INPUT_REPORT;
typedef CONST WINUHID_STEAM_CONTROLLER_INPUT_REPORT* PCWINUHID_STEAM_CONTROLLER_INPUT_REPORT;

typedef struct _WINUHID_STEAM_CONTROLLER_BATTERY_REPORT {
	UCHAR ReportId;
	UCHAR ChargeState;
	UCHAR BatteryLevel;
	USHORT BatteryVoltage;
	USHORT SystemVoltage;
	USHORT InputVoltage;
	USHORT Current;
	USHORT InputCurrent;
	USHORT Temperature;
} WINUHID_STEAM_CONTROLLER_BATTERY_REPORT, *PWINUHID_STEAM_CONTROLLER_BATTERY_REPORT;
typedef CONST WINUHID_STEAM_CONTROLLER_BATTERY_REPORT* PCWINUHID_STEAM_CONTROLLER_BATTERY_REPORT;

typedef struct _WINUHID_STEAM_CONTROLLER_WIRELESS_STATUS_REPORT {
	UCHAR ReportId;
	UCHAR State;
} WINUHID_STEAM_CONTROLLER_WIRELESS_STATUS_REPORT, *PWINUHID_STEAM_CONTROLLER_WIRELESS_STATUS_REPORT;
typedef CONST WINUHID_STEAM_CONTROLLER_WIRELESS_STATUS_REPORT* PCWINUHID_STEAM_CONTROLLER_WIRELESS_STATUS_REPORT;

typedef struct _WINUHID_STEAM_CONTROLLER_FEATURE_REPORT {
	UCHAR ReportId;
	UCHAR Data[WINUHID_STEAM_CONTROLLER_FEATURE_REPORT_BYTES - 1];
} WINUHID_STEAM_CONTROLLER_FEATURE_REPORT, *PWINUHID_STEAM_CONTROLLER_FEATURE_REPORT;
typedef CONST WINUHID_STEAM_CONTROLLER_FEATURE_REPORT* PCWINUHID_STEAM_CONTROLLER_FEATURE_REPORT;

#include <poppack.h>

//
// Optional callback to be invoked when Steam writes HID output or feature reports.
//
// The report buffer includes the numbered report ID as the first byte so callers can
// forward it unchanged to a real remote Steam Controller transport.
//
typedef VOID WINUHID_STEAM_CONTROLLER_RAW_HID_CB(PVOID CallbackContext,
	WINUHID_STEAM_CONTROLLER_RAW_HID_REPORT_TYPE ReportType, CONST UCHAR* Report, ULONG ReportLength);
typedef WINUHID_STEAM_CONTROLLER_RAW_HID_CB* PWINUHID_STEAM_CONTROLLER_RAW_HID_CB;

typedef struct _WINUHID_STEAM_CONTROLLER_INFO {
	//
	// Basic HID and PnP device information (optional)
	//
	PCWINUHID_PRESET_DEVICE_INFO BasicInfo;

	//
	// Optional Steam Controller serial string reported to Steam. If unspecified,
	// a direct-Bluetooth Triton identity captured from real hardware is used.
	//
	PCSTR SerialNumber;

	//
	// Optional firmware attributes reported to Steam. Zero means use captured
	// direct-Bluetooth Triton defaults.
	//
	ULONG FirmwareBuildTime;
	ULONG BoardRevision;
} WINUHID_STEAM_CONTROLLER_INFO, *PWINUHID_STEAM_CONTROLLER_INFO;
typedef CONST WINUHID_STEAM_CONTROLLER_INFO* PCWINUHID_STEAM_CONTROLLER_INFO;

//
// Creates a new 2026 Steam Controller (Triton BLE) device.
//
// To destroy the device, call WinUHidSteamControllerDestroy().
//
// On failure, the function will return NULL. Call GetLastError() for the error code.
//
WINUHID_API PWINUHID_STEAM_CONTROLLER WinUHidSteamControllerCreate(PCWINUHID_STEAM_CONTROLLER_INFO Info,
	PWINUHID_STEAM_CONTROLLER_RAW_HID_CB RawHidCallback, PVOID CallbackContext);

//
// Initializes reports with neutral connected-state data.
//
WINUHID_API VOID WinUHidSteamControllerInitializeInputReport(PWINUHID_STEAM_CONTROLLER_INPUT_REPORT Report);
WINUHID_API VOID WinUHidSteamControllerInitializeBatteryReport(PWINUHID_STEAM_CONTROLLER_BATTERY_REPORT Report);
WINUHID_API VOID WinUHidSteamControllerInitializeWirelessStatusReport(PWINUHID_STEAM_CONTROLLER_WIRELESS_STATUS_REPORT Report, BOOL Connected);

//
// Submits typed input reports to the device.
//
// On failure, these functions will return FALSE. Call GetLastError() for the error code.
//
WINUHID_API BOOL WinUHidSteamControllerReportInput(PWINUHID_STEAM_CONTROLLER Controller, PCWINUHID_STEAM_CONTROLLER_INPUT_REPORT Report);
WINUHID_API BOOL WinUHidSteamControllerReportBattery(PWINUHID_STEAM_CONTROLLER Controller, PCWINUHID_STEAM_CONTROLLER_BATTERY_REPORT Report);
WINUHID_API BOOL WinUHidSteamControllerReportWirelessStatus(PWINUHID_STEAM_CONTROLLER Controller, PCWINUHID_STEAM_CONTROLLER_WIRELESS_STATUS_REPORT Report);

//
// Submits a raw input report that already includes the numbered report ID byte.
//
WINUHID_API BOOL WinUHidSteamControllerReportRawInput(PWINUHID_STEAM_CONTROLLER Controller, LPCVOID Report, ULONG ReportLength);

//
// Destroys the controller.
//
// This function never fails as long as the provided argument is valid.
//
WINUHID_API VOID WinUHidSteamControllerDestroy(PWINUHID_STEAM_CONTROLLER Controller);
